apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
  creationTimestamp: "2026-01-09T17:33:40Z"
  labels:
    app.kubernetes.io/instance: coder
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: coder
    app.kubernetes.io/version: 2.28.0
    helm.sh/chart: coder-2.28.0
  name: coder
  namespace: coder
  resourceVersion: "3547"
  uid: 6f4cb8fd-b96f-4d66-8ab0-84342896622c
